name: "Test and linting"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  verify:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Install beta version
      run: |
        go install golang.org/dl/go1.18beta2@latest
        go1.18beta2 download
        cp $(which go1.18beta2) $(which go)
        go version

    - name: Build
      run: go build ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Test race detector
      run: go test -race -v -cover ./...
